name: Check Pipeline Status

on:
  workflow_call:
    inputs:
      region: # AWS region where pipeline is located
        required: true
        type: string
        default: 'us-west-2'
      pipeline_name: # Name of the pipeline to check
        required: true
        type: string
        default: 'us-west-2-t-bt-mtjngo-pool1-orchestration'
      stage_name: # Name of the stage to check
        required: true
        type: string
        default: 't'

# permission can be added at job level or workflow level
permissions:
  id-token: write # Required to get the ID Token that will be used for OIDC
  contents: read # Required for actions/checkout

jobs:
  check_pipeline_status:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.BUILD_AWS_IAM_ROLE_ARN }}
          role-session-name: OIDCSession
      
      - name: Check pipeline status
        run: |
          set -x

          while true; do
            STATUS=$(aws codepipeline get-pipeline-state --name ${{ inputs.pipeline_name }} --query "stageStates[?stageName=='${{ inputs.stage_name }}' ].latestExecution.status" --output text)
            [ $? -ne 0 ] && exit 1

            if [ "$STATUS" == "InProgress" ]; then
              echo "Pipeline is still in progress"
              sleep 30
            elif [ "$STATUS" == "Succeeded" ]; then
              echo "Pipeline succeeded"
              exit 0
            else
              echo "Pipeline failed"
              exit 1
            fi
          done      
