name: test #used for debugging, not intended to be used in production

on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        default: latest

jobs:
  test: 
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
         echo ${{ inputs.tag_name }}
